import argparse
import os


def stars():
    for a in range(30):
        print'*',


def define_parser():
    # Define program arguments
    parser = argparse.ArgumentParser(description="cBioPortal-Tools (https://github.com/oicr-gsi/cbioportal_tools) is a "
                                                 "command line tool for extracting data from files generated through "
                                                 "the seqware workflows, as well as from tools run outside of the "
                                                 "pipeline, and put them into the correct cBioPortal import files "
                                                 "(https://cbioportal.readthedocs.io/en/latest/File-Formats.html).")

    parser.add_argument("-i", "--study-id",
                        help="This is the cancer study ID, a unique string. Please use the format gene_lab_year. e.g."
                             "brca_gsi_2019",
                        metavar='')
    parser.add_argument("-f", "--study-folder",
                        help="This is the cancer study main directory.",
                        metavar='')
    parser.add_argument("-t", "--type-of-cancer",
                        help="Cancer type abbreviation, e.g.'brca' or 'mixed' for multiple types.",
                        metavar='')
    parser.add_argument("-d", "--default",
                        action="store_true",
                        help="Prevents need for user input by trying to parse study ID, you must follow format "
                             "indicated in the help if you use this")
    # Still need to collect the name and the description
    return parser


def change_folder(folder):
    original_working_directory = os.getcwd()
    try:
        os.chdir(folder)
    except OSError:
        stars()
        print 'The path to your folder probably does not exist. Trying to make the folder for you.'
        stars()
        try:
            os.mkdir(folder)
        except OSError:
            stars()
            raise ValueError('You may not have permission to create folders there. Very sad')
    return original_working_directory


def save_meta_cancer_study(args):
    study_id = args.study_id
    type_of_cancer = args.type_of_cancer
    if not args.default:
        print("Write a description of the study below e.g. 'Comprehensive profiling of 103 breast cancer samples. "
              "Generated by Genome Sequence Informatics 2019.: ")
        description = raw_input()
        print("Please write the name of the study e.g. 'Breast Cancer (Genome Sequence Informatics 2019):'")
        name = raw_input()
        print("Now write the short name e.g. 'BRCA (GSI)': ")
        short_name = raw_input()
    else:
        split = study_id.split('_')
        description = 'Cancer study on {} by {} conducted in {}.'.format(*split)
        split[0] = split[0].upper()
        split[1] = split[1].upper()
        name = '{} {} ({})'.format(*split)
        short_name = '{} ({})'.format(*split)

    f = open('meta_study.txt', 'w+')
    f.write('type_of_cancer: ' + type_of_cancer + '\n')
    f.write('cancer_study_identifier: ' + study_id + '\n')
    f.write('name: ' + name + '\n')
    f.write('description: ' + description + '\n')
    f.write('short_name: ' + short_name + '\n')
    f.close()


def reset_folder(owd):
    os.chdir(owd)


def main():
    args = define_parser().parse_args()

    original_dir = change_folder(args.study_folder)
    save_meta_cancer_study(args)
    reset_folder(original_dir)


if __name__ == '__main__':
    main()
